cameras:
  cam_p1b_rtsp_replay:
    enabled: true
    source_id: p1b_rtsp_replay
    name: P1b RTSP Replay Manual Sink POC
    rtsp_url: rtsp://10.37.57.112:8554/live/1080movie
    gpu_id: 0
    zones:
      p1b_rtsp_full_frame:
        type: polygon
        points:
          - [0.0, 0.0]
          - [1920.0, 0.0]
          - [1920.0, 1080.0]
          - [0.0, 1080.0]
    rules:
      intrusion:
        enabled: true
        zone: p1b_rtsp_full_frame
        severity: medium
        cooldown_s: 1
        clip_required: false
        min_inside_ms: 1
        snapshot_required: false
